name = "artwork-archivetune.koiiverse.cloud"
main = "src/index.ts"
compatibility_date = "2026-01-01"

[[kv_namespaces]]
binding = "CACHE"
id = "6a7339b7c87c47e493a561f7cc68caa0"
preview_id = "1273e9570f48400a8847c10a3e28bbf8"

[observability]
[observability.logs]
enabled = true
invocation_logs = true
